# Generated by Django 3.0.8 on 2020-07-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20200709_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
