# Generated by Django 3.0.8 on 2020-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20200709_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AddField(
            model_name='animal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
